shop/urls.py
from os import name
from django.contrib import admin
from django.urls import path, re_path

from django.conf.urls import url
from shop.views import *

app_name = 'shop'

urlpatterns = [
    path('my-shop/', myShopProducts, name='my_shop'),
    path('add-product/', addProduct, name='add_product'),
    path('edit-product/<int:id>', editProduct, name='edit_product'),
    path('add-type-brand/', addProductTypeBrand, name='add_type_brand'),
    # path('add-type', addType, name='addType'),
    path('add-excel/', addProductFromExcel, name = 'add_excel'),
    path('store/', shopStore, name = 'store'),
    path('search-self-store/', searchMyStore, name= 'search_self_store'),
    path('testbr/', barCodeGenerator),

    path('sell/sellProduct/', sellProduct, name='sell_product'),
    path('all-sell/', allSell, name="all_sell"),

    path('filter-sell/', filterSell, name= "filter_sell")
]

shop_management/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from products.views import *
from account.views import LoginView, LogoutView

from django.conf import settings
from django.views.static import serve
urlpatterns = [
    # path('', home, name = 'home'),

    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('super-admin/', include('super_admin.urls')),

    # path('super-admin/', include('super_admin.urls')),
    

    path('', productList, name = 'all_products'),
    
    path('admin/', admin.site.urls),

    
    

]



urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

super_admin/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

from django.conf.urls import url
from super_admin.views import *
app_name = 'super_admin'

urlpatterns = [
    
    path('dashboard/', superAdminDashboard, name='dashboard'),
    path('add-shop/', addShop, name='add_shop'),
    path('all-shop/', allShopList, name='all_shop'),
    path('add-type-brand/', addProductTypeBrand, name='add_type_brand'),
    path('delete-type/<int:id>', deleteProductType, name='delete_product_type'),
    path('delete-brand/<int:id>', deleteBrand, name='delete_brand'),
    
]

super_admin/models.py
from django.db import models

# Create your models here.

super_admin/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib import messages, auth
from django.db.models import Q
from account.models import *
from shop.models import ShopDetail
from shop.forms import ShopCreateForm, ShopDetailForm
from account.models import *
from account.forms import *
from products.models import *
from products.forms import *

def superAdminDashboard(request):
    template_name = 'super_admin/dashboard.html'

    return render(request, template_name, {})

def addShop(request):
    template_name = 'super_admin/add_shop.html'
    shop_form = ShopCreateForm
    shop_detail_form = ShopDetailForm
    if request.method == 'POST':
        shop_form = ShopCreateForm(request.POST)
        shop_detail_form = ShopDetailForm(request.POST)
        print(shop_form)
        if shop_form.is_valid():
            print('form is valid')
            shop = shop_form.save(commit=False)
            password = shop_form.cleaned_data.get('password')
            shop.set_password(password)
            shop.is_staff = False
            shop.is_superuser = False
            shop.user_type = UserType.objects.get(user_type='shop')         ## defining user_type as doctor for user table
            shop.is_active = True
            print("shop create form saved")
            shop.save()
        if shop_detail_form.is_valid:
            shop_details = shop_detail_form.save(commit=False)
            this_shop_email = shop_form.cleaned_data.get('email')
            this_shop = User.objects.get(email = this_shop_email)
            shop_details.shop = this_shop
            shop_details.save()


    context = {
        'shop_form':shop_form,
        'shop_detail_form':shop_detail_form
    }

    return render(request, template_name, context)

def allShopList(request):
    template_name = 'super_admin/all_shop.html'
    all_shop = ShopDetail.objects.all()
    print(all_shop)
    context = {
        'all_shop':all_shop
    }
    return render(request, template_name, context)

def addProductTypeBrand(request):
    template_name = 'super_admin/product_type_brand.html'
    all_product_type = ProductType.objects.all()
    all_brand = Brand.objects.all()
    product_type_form = ProductTypeForm
    product_brand_form = BrandForm

    context = {
        'product_brand_form': product_brand_form,
        'product_type_form': product_type_form,
        'all_product_type': all_product_type,
        'all_brand': all_brand
    }

    if request.method == 'POST':
        product_type_form = ProductTypeForm(request.POST)
        product_brand_form = BrandForm(request.POST)
        if product_type_form.is_valid():
            product_type_form.save()
        if product_brand_form.is_valid():
            product_brand_form.save()

    return render(request, template_name, context)

def deleteProductType(request, id=None):
    this_product_type = ProductType.objects.get(id = id)
    this_product_type.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def deleteBrand(request, id=None):
    this_brand = Brand.objects.get(id = id)
    this_brand.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/super_admin/add_shop.html
{% extends 'super_admin_base.html' %}

{% block title %}
Add New Shop
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="content-wrapper">

    
        <section class="content">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-md-12">
                        <p class="content_heading">Add New Shop</h3>
                    </div>

                    
                </div> 

                <div class="com-md-12 d-flex flex-row justify-content-center">
                    <div class="col-lg-4 col-md-5 col-sm-6">
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger col-md-5 col-lg-4 col-sm-6 alert-dismissable">
                                    <a href="#" class="close" data-dismiss='alert' aria-label='close'>&times;</a>
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger alert-dismissable">
                                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>

                <div class="col-md-12 d-flex flex-row justify-content-center">  
                    <div class="col-md-10 col-lg-10 col-sm-12 new_entry_form p-5 pt-4 shadow form-content">

                        <form method="post" action="">
                            {% csrf_token %}

                    <div class="row">
                        <div class="col-md-10 p-3">
                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="name" class=" col-form-label">*Shop Name :</label>
                                </div>
                                
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="text" name="first_name" class="form-control" id="first_name" placeholder="shop name"/>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="phone" class=" col-form-label">Phone Number :</label>
                                </div>
                               
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="text" name="phone" class="form-control" id="phone" placeholder="phone no"/>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="shop owner name" class=" col-form-label">Shop Owner Name :</label>
                                </div>
                                
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="text" name="shop_owner_name" class="form-control" id="owner_name" placeholder="Shop name"/>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="shop_owner_number" class=" col-form-label">Shop Owner Number :</label>
                                </div>
                                
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="text" name="shop_owner_phone" class="form-control" id="owner_number" placeholder="Shop owner number"/>
                                </div>
                            </div>

                            
                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="shop_address" class=" col-form-label">Shop Address :</label>
                                </div>
                                
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="text" name="shop_address" class="form-control" id="address" placeholder="shop address"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="email" class=" col-form-label">*Email :</label>
                                </div>
                                
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="email" name="email" class="form-control" id="email" placeholder="email"/>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-4 col-md-4 m-0 p-0 ml-4">
                                    <label for="password" class="col-form-label">*Password :</label>
                                </div>
                                
                                <div class="col-lg-7 col-md-7 m-0 p-0">
                                    <input type="password" name="password"  class="form-control" id="password" placeholder="password"/>
                                </div>
                            </div>
                            
                            
                        </div>  
                    </div> 

                    <div class="form-row text-center">
                        <div class="col-12">
                            <div class="">
                                
                                <button type="submit" class="btn btn-outline-dark col-md-4 col-lg-4">Save</button>
                            </div> 
                        </div>  <!--/.col -->
                    </div> 
                </form>

                    </div> 
                </div> 
                
            </div>  <!-- /.container-fluid -->
        </section>   <!-- /.content -->
    </div>   <!-- /.content-wrapper -->
</div>
{% endblock %}

templates/super_admin/all_shop.html
{% extends 'super_admin_base.html' %}

{% block title %}
Add New Shop
{% endblock %}

{% block content %}
<div class="wrapper">
    <div class="content-wrapper">
        <section class="content">
            <div class="cls1">
                <div class="col-12">
                    <div class="">
                        <div class="">
                            <div class="row">
                            
                            
                            <div class="col-md-12">
                              <p class="content_heading">List of Shops</p>
                          </div>
                            </div>  
                        </div>  
      
                        <div class="">
                            <div class="row col-md-12 p-0 m-0 d-flex flex-row justify-content-center">
                              <!-- Search form -->
                              <div class="active-cyan-4 mb-2 col-md-4 col-lg-3 col-sm-4 col-8 ml-0">
                                <form class="d-flex flex-row" method="get" action="#">
                                  <input class="form-control" type="text" placeholder="Search shop" aria-label="Search" name="shop_search_parameter">
                                  <button type="submit" class="btn btn-info">Search</button>
                                </form>
                              </div>
                              <div class="col-md-9 col-lg-9 col-sm-4 col-8 float-right mr-0">
                                <button type="submit" class="btn btn-secondary active float-right">
                                    <a href="#" style="color:white;">+ Add New shop</a></button>
                              </div>
                              <div class="row col-lg-12 col-md-12 col-sm-12 col-12 justify-content-center">
                                <table id="shop_list" class="table table-borderless table-hover col-auto col-md-12 table-responsive table-striped">
                                  <thead class="">
                                      <tr>
                                          <th>Shop name</th>
                                          <th>Shop Phone Number</th>
                                          <th>Shop Address</th>
                                          <th>Shop Type</th>
                                          <th>Shop Owner Name</th>
                                          <th>Shop Owner Phone</th>
                                          <th>Email</th>
                                          <th>Active Status</th>
                                      </tr>
                                  </thead>
        
                                  <tbody class="">
                                      
                                      {% for shop in all_shop %}
                                      <tr>
                                        
                                        <td>{{ shop.shop.first_name }}</td>
                                        <td>{{ shop.phone }}</td>
                                        <td>{{ shop.shop_address }}</td>
                                        <td>{{ shop.shop_type }}</td>
                                        <td>{{ shop.shop_owner_name }}</td>
                                        <td>{{ shop.shop_owner_phone }}</td>
                                        <td>{{ shop.shop.email }}</td>
                                        {% if shop.shop.is_active == True %}
                                            <td><input type="checkbox" id="{{ shop.info.id }}" name="" value="" checked ></td>
                                        {% else %}
                                            <td><input type="checkbox" id="{{ shop.info.id }}" name="" value="" ></td>
                                        {% endif %}
                                        
                                        <!-- <td>
                                          <input type="checkbox" id="{{ shop.info.id }}" name="" value="" onchange="showConfirmButtons(this)"
                                           {% if shop.info.is_active %} checked {% endif %}
                                          >
                                          
                                          <div id="id{{shop.info.id}}" style="display: none;">
                                            <button class="btn btn-danger" onclick="confirmChangeshop('{{ shop.info.id }}')">Yes</button>
                                            <button class="btn btn-primary" onclick="cancelChange('{{ shop.info.id }}')">No</button>
                                          </div>
                                        </td> -->
                                        
      
                                        <!-- <td class="">    
                                            <a href="{{ shop.info.get_absolute_url }}">
                                                <button class="btn btn-secondary" style="font-size:12px;">
                                                  View Details
                                                </button></a>
                                        </td> -->
                                    </tr>
                                    {% endfor %}
                                  </tbody>
                              </table>  
                            </div>

                              
                          </div>    
                        </div> 
                    </div> 
                </div>  <!-- /.col -->
            </div>  <!-- /.row -->
        </section>  <!-- /.content -->
    
       
    </div>
</div>
{% endblock %}

templates/super_admin/dashboard.html
{% extends 'super_admin_base.html' %}

{% block title %}
Modern Shop Admin Dashboard
{% endblock %}


{% block content %}
<P>{{ request.user.first_name }}</P>
{% endblock %}

templates/super_admin/product_type_brand.html
{% extends 'super_admin_base.html' %}

{% block title %}
Add New Shop
{% endblock %}

{% block content %}
<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="row justify-content-center">
        <div class="col-lg-5 col-md-5 col-sm-11">
            <div>
                <h2>All Product Type</h2>
                
                {% for product_type in all_product_type %}
                    <div class="row">
                        <p>{{ product_type.type_name }}</p>
                        <a class="btn btn-secondary float-right" href="{% url 'super_admin:delete_product_type' id=product_type.id %}">Delete</a>
                    </div>
                {% endfor %}
                
            </div>
    
            <div>
                <h2>Add product Type</h2>
    
                <form method="POST"> {% csrf_token %}
                {{ product_type_form.as_p }}
                <input type="submit", value="save" />
                </form>
            </div>
        
        </div>
    
        <div class="col-lg-5 col-md-5 col-sm-11">
            <div>
                <h2>All Product Brand</h2>
               
                {% for brand in all_brand %}
                <div class="row">
                    <p>{{ brand.brand_name }}</p>
                    <a class="btn btn-secondary float-right" href="{% url 'super_admin:delete_brand' id=brand.id %}">Delete</a>
                </div>
                {% endfor %}
               
            </div>
    
            <div>
                <h2>Add New Brand</h2>
    
                <form method="POST"> {% csrf_token %}
                    {{ product_brand_form.as_p }}
                    <input type="submit", value="save" />
                </form>
            </div>
        
        </div>
    
    </div>
</div>


{% endblock %}