account/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

from django.conf.urls import url
from account.views import *
app_name = 'account'

urlpatterns = [
    
    path('login/', LoginView.as_view(), name='login_page'),
    path('logout/', LogoutView.as_view(), name='logout' ),
    path('super-admin-register/', SuperAdminRegistrationView.as_view(), name='super_admin_register'),
]

shop/urls.py
from os import name
from django.contrib import admin
from django.urls import path, re_path

from django.conf.urls import url
from shop.views import *

app_name = 'shop'

urlpatterns = [
    path('my-shop/', myShopProducts, name='my_shop'),
    path('add-product/', addProduct, name='add_product'),
    path('edit-product/<int:id>', editProduct, name='edit_product'),
    path('add-type-brand/', addProductTypeBrand, name='add_type_brand'),
    # path('add-type', addType, name='addType'),
    path('add-excel/', addProductFromExcel, name = 'add_excel'),
    path('store/', shopStore, name = 'store'),
    path('search-self-store/', searchMyStore, name= 'search_self_store'),
    path('testbr/', barCodeGenerator),

    path('sell/sellProduct/', sellProduct, name='sell_product'),
    path('all-sell/', allSell, name="all_sell"),

    path('filter-sell/', filterSell, name= "filter_sell")
]

shop_management/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from products.views import *
from account.views import LoginView, LogoutView

from django.conf import settings
from django.views.static import serve
urlpatterns = [
    # path('', home, name = 'home'),

    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('super-admin/', include('super_admin.urls')),

    # path('super-admin/', include('super_admin.urls')),
    

    path('', productList, name = 'all_products'),
    
    path('admin/', admin.site.urls),

    
    

]



urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

account/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from account.manager import CustomUserManager

import datetime
import os



# from multiselectfield import MultiSelectField

class UserType(models.Model):
    user_type = models.CharField(max_length=15, blank=False, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user_type

class User(AbstractUser):
    username = None
    user_type = models.ForeignKey(UserType, on_delete=models.CASCADE)
    email = models.EmailField(unique=True, blank=False, error_messages={
        'required': "User_type must be defined",
        'unique': "A user already exist"
    })
    phone = models.CharField(max_length=18, blank=True, default='')
    updated_at = models.DateTimeField(auto_now=True) 


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse('meditech_admin:client_detail', args=[str(self.id)])

shop/models.py
from django.db import models
from account.models import User, UserType
# Create your models here.


class ShopDetail(models.Model):
    shop = models.ForeignKey(User, on_delete=models.CASCADE)
    shop_owner_name = models.CharField(max_length=25, blank=True, default='')
    shop_owner_phone = models.CharField(max_length=20, blank=True, default='')
    shop_type = models.CharField(max_length= 15, blank=True, default='')
    shop_address = models.CharField(max_length= 50, blank=True, default='')
    updated_at = models.DateTimeField(auto_now=True)

    def __int__(self):
        return self.id

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

import re

from account.models import *
from django.forms.widgets import DateInput


from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class AdminRegistrationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(AdminRegistrationForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['email'].required = True
        self.fields['password1'].required = True
        self.fields['password2'].required = True

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2', 'phone']

        error_messages = {
             'first_name': {
                'required': 'Name is required',
            },
            'email': {
                'required': 'email is required.'
            },
            'password1': {
                'required': 'Password is required.'
            },
            'password2': {
                'required': 'Confirm password is required.'
            },
        }

    def passwordMatching(self, *args, **kwargs):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError('password missmatchd')
        else:
            pass

    def save(self, commit=True):
        user = super(AdminRegistrationForm, self).save(commit=False)
        user.user_type = UserType.objects.get(user_type='admin')
        if commit:
            user.save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        label= "Password",
        strip=False,
        widget=forms.PasswordInput,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None
        self.fields['email'].widget.attrs.update({'placeholder': 'Please enter Email'})
        self.fields['password'].widget.attrs.update({'placeholder': 'Please enter Password'})
        
    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user = authenticate(email= email, password= password)

            if self.user is None:
                raise forms.ValidationError("Email or password is invalid")
            if not self.user.check_password(password):
                raise forms.ValidationError("Password does not match")
            if not self.user.is_active:
                raise forms.ValidationError("User is not active")

        return super(LoginForm, self).clean(*args, **kwargs)

    def get_user(self):
        return self.user

shop/forms.py
from django import forms

from account.models import User, UserType
from shop.models import ShopDetail

import re

from django.core.exceptions import ValidationError


class ShopCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'password', 'phone', 'is_active']

        error_messages = {
             'first_name': {
                'required': 'Name is required',
            },
            'email': {
                'required': 'email is required.'
            },
            'password': {
                'required': 'Password is required.'
            },
            'phone': {
                'required': 'Phone is important.'
            },
        }
    def __init__(self, *args, **kwargs):
        super(ShopCreateForm, self).__init__(*args, **kwargs)
       
        self.fields['phone'].required = True
        self.fields['first_name'].required = True
        self.fields['password'].required = True

    def clean_phone(self, *args, **kwargs):
        phone = self.cleaned_data.get('phone')
        if len(phone) < 11:
            raise forms.ValidationError("phone number is too short")
        elif re.search('[a-zA-Z]', phone):
            raise forms.ValidationError("Invalid phone number")
        else:
            return phone

class ShopDetailForm(forms.ModelForm):
    class Meta:
        model = ShopDetail
        fields = ['shop_owner_name','shop_owner_phone', 'shop_type', 'shop_address']

account/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, FormView, RedirectView
from django.core.mail import send_mail, EmailMessage, EmailMultiAlternatives
from django.core.paginator import Paginator
from django.contrib import messages, auth
from django.db.models import Q
from account.models import *

from account.models import *
from account.forms import *

from datetime import datetime, date, time, timezone
# Create your views here.

class LoginView(FormView):                                           ##----------- View function for login. Extending Django FormView class
    super_admin_success_url= '/super-admin/dashboard/'               ##----------- success url if logged in as user_type == admin
    shop_success_url= '/shop/my-shop/'
    # doctor_success_url= '/doctor/dashboard/'
    # manager_success_url= '/manager/dashboard/'
    # general_staff_success_url= '/staff/dashboard/'

    general_success_url= '/'                                         ##----------- if user type is undefined


    form_class = LoginForm
    template_name = "account/login.html"

    extra_context = {
        'title': 'Login'
    }
    # user_role = UserType.objects.get(user_type='admin')

    def dispatch(self, request, *args, **kwargs):                     ##----------- Track and redirect as the requisting user is authenticated 
        if self.request.user.is_authenticated:
            return redirect(self.get_success_url())                   ##----------- if authenticated redirect to success url as user_type
        return super().dispatch(self.request, *args, **kwargs)        ##----------- if not authenticated redirect to login page

    def get_success_url(self):                                        ##----------- finds the correct success url as user_type
        if 'next' in self.request.GET and self.request.GET['next'] != '':
            return self.request.GET['next'] 

        else:
            if self.request.user.user_type == UserType.objects.get(user_type='admin'):                ##----------- if admid return the admin dashboard
                print(self.request.user.user_type)
                return self.super_admin_success_url
            if self.request.user.user_type == UserType.objects.get(user_type='shop'):                ##----------- if client return the client dashboard
                print(self.request.user.user_type)
                return self.shop_success_url
            # if self.request.user.user_type == UserType.objects.get(user_type='doctor'):                ##----------- if doctor return the doctor dashboard
            #     print(self.request.user.user_type)
            #     return self.doctor_success_url
            # if self.request.user.user_type == UserType.objects.get(user_type='manager'):                ##----------- if manger return the manager dashboard
            #     print(self.request.user.user_type)
            #     return self.manager_success_url
            # if self.request.user.user_type == UserType.objects.get(user_type='general_staff'):                ##----------- if general_staff return the general_staff dashboard
            #     print(self.request.user.user_type)
            #     return self.general_staff_success_url
            else:
                print(self.request.user.user_type)
                return self.general_success_url


    def get_form_class(self):                                         ##----------- get the form of this class
        print(self.form_class(data=self.request.POST))
        return self.form_class

    def form_valid(self, form):                                       ##----------- if submited form is valid get the user and call success_url
        print("valid Form")
        auth.login(self.request, form.get_user())

        # write_log(self.request, self.request.user, "Logged In", CHANGE)

        return redirect(self.get_success_url())

    def form_invalid(self, form):
        print("invalid form")
        return self.render_to_response(self.get_context_data(form=form)) ##------ if submited form is invalid load the form again

    # return render(request, 'login.html', {})

class LogoutView(RedirectView):                                          ##------ Control if user is logging out

    url = '/account/login/'                                                      ##------ url after logout

    def get(self, request, *args, **kwargs):

        # write_log(self.request, self.request.user, "Logged Out", CHANGE)

        auth.logout(request)
        print('Logged out')
        print(request.user)
        messages.success(request, "You are logged out")
        return super(LogoutView, self).get(request, *args, **kwargs)



def passwordReset(request):                                              ##-------- This function is to reset passwod
    if request.method == 'POST':
        email = request.POST.get('email')
        pass1= request.POST.get('password1')
        pass2= request.POST.get('password2')
        # print(email)
        try: 
            email= User.objects.get(email=email)
            if email:                                                    ##-------- Checking if the given email is into user table (registered)
                if pass1 == pass2:                                       ##-------- confirming the new password
                    email.set_password(pass1)                            ##-------- set new password
                    email.save()                                         ##-------- save the password
            return redirect('login_page')                                ## ------- after successful reset redirect to login page
        except Exception as e:
            print(e)
            context = {'message':"You are not registered"}
            return render(request, 'reset_password.html', context)      ##--------- if given email is wrong render with message
    return render(request, 'reset_password.html', {})


# ------------ class to create new meditech admin-------------------------
class SuperAdminRegistrationView(CreateView):
    model = User
    form_class = AdminRegistrationForm
    template_name = 'account/super_admin_register.html'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):                       ##----------- Track and redirect as the requisting user is authenticated
        if self.request.user.is_authenticated:
            return redirect('home')
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):                           ##----------- if request is post
        form = self.form_class(data=request.POST)                       ##----------- assigning form with post data
        # print(form)
        try:
            if form.is_valid():
                user = form.save(commit=False)                          ##----------- commit=false gets and model and make the form(with data)
                                                                        ##----------- editable and change the data into form
                password = form.cleaned_data.get('password1')
                
                user.set_password(password)
                user.is_superuser = True
                user.is_staff = True
                
                user.save()
                return redirect('home')        ##---------- redirect to admin dashboard if successful
            else:
                return render(request, 'account/super_admin_register.html', {'form':form})
        except Exception as e:
            print(e)
    #return render(request, 'meditech_admin/meditech_admin_register.html')


def insert_data_in_userType():

    count = UserType.objects.all().count()

    if count == 0:
        obj = UserType()
        obj.id = 1
        obj.user_type = 'admin'
        obj.save()

        obj = UserType()
        obj.id = 1
        obj.user_type = 'shop'
        obj.save()

        obj = UserType()
        obj.id = 1
        obj.user_type = 'customer'
        obj.save()

templates/shop/accounts.html
{% extends 'admin_base.html' %}
{% block title %}
    Modern Shop
{% endblock %}

{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
  
  
    <!-- Main content -->
    <section class="content">
        <div class="search-filter-section-shop pt-2">
            <div class="product-view">
                <div class="container-fluid">
                    <div class="row product-list-section justify-content-center">
                        <div class="col-lg-12 col-md-12 p-1">
                            <div class="row m-0">
                                <div class="col-md-12 product-search-heading">
                                    <h4 class="text-center text-uppercase">All Sell List</h4>
                                </div>
                                <div class="col-lg-12 col-md-12 m-0 shadow mt-2 mb-4">
                                    
                                    <div class="product-view-top">
                                        <form method="get" action="{% url 'shop:filter_sell' %}">
                                        <div class="row">
                                        
                                            <div class="col-md-4">
                                                <div class="product-search justify-content-center row">
                                                    <label class="search_form_shop_account_label">Date </label>
                                                    <input type="date" class="search_form_shop_account_input" value="" name="from_date" placeholder="from">
                                                    <label class="search_form_shop_account_label"> -- </label>
                                                    <input type="date" class="search_form_shop_account_input" value="" name="to_date" placeholder="to">
                                                    
                                                </div>
                                            </div>
                                           
                                            <div class="col-md-4">
                                                <div class="product-search justify-content-center row">
                                                    <label class="search_form_shop_account_label">Monthly </label>
                                                    <select type="" class="search_form_shop_account_input" value="" name="month" placeholder="from">
                                                        <option value="">Of This Year</option>
                                                        <option value="01">January</option>
                                                        <option value="02">February</option>
                                                        <option value="03">March</option>
                                                        <option value="04">April</option>
                                                        <option value="05">May</option>
                                                        <option value="06">June</option>
                                                        <option value="07">July</option>
                                                        <option value="08">Auguest</option>
                                                        <option value="09">September</option>
                                                        <option value="10">October</option>
                                                        <option value="11">November</option>
                                                        <option value="12">December</option>
                                                    </select>
                                                    <label class="search_form_shop_account_label">Yearly </label>
                                                    <select type="" class="search_form_shop_account_input" value="" name="year" placeholder="from">
                                                        <option value="">Select year</option>
                                                        <option value="2021">2021</option>
                                                        <option value="2020">2020</option>
                                                        <option>2019</option>
                                                        <option>2018</option>
                                                    </select>
                                                    
                                                </div>
                                            </div>
                                            <div class="row col-md-4 justify-content-end">
                                                <div class="product-search justify-content-center row">
                                                    <label class="search_form_shop_account_label">Product </label>
                                                    <input class="product-search_form_shop_account_label" type="text" value="" name="product" placeholder="name/ bar-code">
                                                        
                                                  
                                                </div>
                                            </div>
                                            
                                        
                                            
                                        
                                        </div>
                                        <div class="row text-center mt-3" >
                                            <div class="col-12 mt-2">
                                                <button class="btn btn-outline-dark col-md-4 col-lg-4">Search Sell</button>
                                            </div>
                                            
                                        </div>
                                        </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-12 p-0">
            <div class="row col-md-12 p-0 m-0 d-flex flex-row justify-content-center p-0">
                <div class="row col-lg-12 col-md-12 col-sm-12 col-12 justify-content-center p-0">
                    <div class="product-list-table" >
                        <table id="" class="custom-table table table-hover col-auto col-md-12 table-responsive pt-2 table-striped">
                            <thead class="ml-auto">
                                <tr>
                                    <th>S.N.</th>
                                    <th>P Name</th>
                                    <th>Bar code</th>
                                    <th>Image</th>
                                    <th>Buying price</th>
                                    <th>Selling Price</th>
                                    <th>Profit</th>
                                    <th>Selling date</th>
                                </tr>
                            </thead>

                            <tbody class="">
                                {% for sell in all_sell %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ sell.product.name }}</td>
                                    <td>{{ sell.product.bar_code }}</td>
                                    <td>
                                        <img style="height: 30px; width: 30px;" src="{{ sell.product.p_image.url }}" alt="">
                                    </td>
                                    <td>{{ sell.product.buying_price }}</td>
                                    <td>{{ sell.selling_price }}</td>

                                    <td>{{ sell.profit }}</td> 
                                    
                                    <td>{{ sell.created_at }}</td> 

                                </tr>
                                
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>  
    </section>  <!-- /.content -->
</div>  <!-- /.content-wrapper -->



{% endblock %}

templates/shop/dashboard.html
{% extends 'admin_base.html' %}

{% block title %}
Modern Shop Admin Dashboard
{% endblock %}


{% block content %}
<P>{{ request.user.first_name }}</P>
{% endblock %}

templates/shop/my_shop.html
{% extends 'admin_base.html' %}
{% block title %}
    Modern Shop
{% endblock %}

{% block content %}

<!-- Product List Start -->
<div class="product-view">
    <div class="container-fluid">
        <div class="row product-list-section justify-content-center">
            <div class="col-lg-12 col-md-12 p-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="product-view-top">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="product-search">
                                        <input type="email" value="Search">
                                        <button><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="product-short">
                                        <div class="dropdown">
                                            <div class="dropdown-toggle" data-toggle="dropdown">Product short by</div>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="#" class="dropdown-item">Newest</a>
                                                <a href="#" class="dropdown-item">Popular</a>
                                                <a href="#" class="dropdown-item">Most sale</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="product-price-range">
                                        <div class="dropdown">
                                            <div class="dropdown-toggle" data-toggle="dropdown">Product price range</div>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a href="#" class="dropdown-item">$0 to $50</a>
                                                <a href="#" class="dropdown-item">$51 to $100</a>
                                                <a href="#" class="dropdown-item">$101 to $150</a>
                                                <a href="#" class="dropdown-item">$151 to $200</a>
                                                <a href="#" class="dropdown-item">$201 to $250</a>
                                                <a href="#" class="dropdown-item">$251 to $300</a>
                                                <a href="#" class="dropdown-item">$301 to $350</a>
                                                <a href="#" class="dropdown-item">$351 to $400</a>
                                                <a href="#" class="dropdown-item">$401 to $450</a>
                                                <a href="#" class="dropdown-item">$451 to $500</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if 'search-product' in request.path %}
                        <div class="col-md-12 product-search-heading">
                            <h4 class="text-uppercase text-center">Search Result</h4>
                        </div>
                    {% else %}
                    <div class="col-md-12 product-search-heading">
                        <h4 class="text-uppercase text-center">All Products</h4>
                    </div>
                    {% endif %}
                    
                        {% for product in all_products %}
                        <div class="col-md-3 p-2 each-product-into-list">

                            
                            
                            <div class="product-item ">
                               
                                <div class="product-image">
                                    <a href="product-detail.html">
                                        <div class="product-list-image">
                                            <img src="{{ product.p_image.url }}" alt="Product Image" class="p-4">
                                        </div>
                                        
                                    </a>
                                    
                                </div>
                                <div class="product-title p-5">
                                    <a href="#" class="product-name"><p>{{ product.name }}</p></a>
                                    
                                </div>
                                <div class="product-price px-5">
                                    <p>{{ product.buying_price }}<span> tk.</span></p>
                                    <a class="btn btn-outline-secondary" type="button" href="{% url 'shop:edit_product' id=product.id %}">Edit</a>
                                </div>
                            </div>
                            
                        </div>
                        {% endfor %}
                    
                    
                </div>
                
                <!-- Pagination Start -->
                <div class="col-md-12">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                            <li class="page-item active"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- Pagination Start -->
            </div>           
            
            
        </div>
    </div>
</div>
<!-- Product List End -->  


{% endblock %}