account/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

from django.conf.urls import url
from account.views import *
app_name = 'account'

urlpatterns = [
    
    path('login/', LoginView.as_view(), name='login_page'),
    path('logout/', LogoutView.as_view(), name='logout' ),
    path('super-admin-register/', SuperAdminRegistrationView.as_view(), name='super_admin_register'),
]

products/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern


from products.views import searchProduct
app_name = 'products'

urlpatterns = [
    path('search-product/', searchProduct, name='search_product')
]

shop/urls.py
from os import name
from django.contrib import admin
from django.urls import path, re_path

from django.conf.urls import url
from shop.views import *

app_name = 'shop'

urlpatterns = [
    path('my-shop/', myShopProducts, name='my_shop'),
    path('add-product/', addProduct, name='add_product'),
    path('edit-product/<int:id>', editProduct, name='edit_product'),
    path('add-type-brand/', addProductTypeBrand, name='add_type_brand'),
    # path('add-type', addType, name='addType'),
    path('add-excel/', addProductFromExcel, name = 'add_excel'),
    path('store/', shopStore, name = 'store'),
    path('search-self-store/', searchMyStore, name= 'search_self_store'),
    path('testbr/', barCodeGenerator),

    path('sell/sellProduct/', sellProduct, name='sell_product'),
    path('all-sell/', allSell, name="all_sell"),

    path('filter-sell/', filterSell, name= "filter_sell")
]

shop_management/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from products.views import *
from account.views import LoginView, LogoutView

from django.conf import settings
from django.views.static import serve
urlpatterns = [
    # path('', home, name = 'home'),

    path('account/', include('account.urls')),
    path('products/', include('products.urls')),
    path('shop/', include('shop.urls')),
    path('super-admin/', include('super_admin.urls')),

    # path('super-admin/', include('super_admin.urls')),
    

    path('', productList, name = 'all_products'),
    
    path('admin/', admin.site.urls),

    
    

]



urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

super_admin/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

from django.conf.urls import url
from super_admin.views import *
app_name = 'super_admin'

urlpatterns = [
    
    path('dashboard/', superAdminDashboard, name='dashboard'),
    path('add-shop/', addShop, name='add_shop'),
    path('all-shop/', allShopList, name='all_shop'),
    path('add-type-brand/', addProductTypeBrand, name='add_type_brand'),
    path('delete-type/<int:id>', deleteProductType, name='delete_product_type'),
    path('delete-brand/<int:id>', deleteBrand, name='delete_brand'),
    
]

templates/admin_base.html
{% load static %}
{% load custom_tags %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
    href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
        href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
        id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

<title>{% block title %}Title here {% endblock %}</title>
  </head>
  <body class="font-family-sans-serif">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'all_products' %}">MODERN</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'all_products' %}">+8801986395483</a>
          </li>
          
          
        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons d-flex flex-row justify-content-start">
                    
          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle  login_link" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
              <i class='fas fa-user-alt' style='font-size:18px;color:rgb(236, 236, 236)'></i>
              {{ request.user.first_name }}        
            <span class="sr-only">(current)</span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'account:logout' %}" class="">
                 Log out
              </a>
          </li>
          
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <nav class="second-navebar navbar-expand-lg navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse pt-4" id="navbarTogglerDemo01">
        
        <ul class="navbar-nav mr-auto mt-2">
          <li class="shop-second-nav-item nav-item">
            <a class="nav-link" href="{% url 'shop:my_shop' %}">My Shop <span class="sr-only">(current)</span></a>
          </li>
          
          <li class="shop-second-nav-item nav-item">
            <a class="nav-link" href="{% url 'shop:add_type_brand' %}">Dashboard</a>
          </li>
          <li class="shop-second-nav-item nav-item">
            <a class="nav-link" href="{% url 'shop:add_product' %}">Add Product</a>
          </li>
          <li class="shop-second-nav-item nav-item">
            <a class="nav-link" href="{% url 'shop:add_excel' %}">Add with Excel</a>
          </li>
          <li class="shop-second-nav-item nav-item">
            <a class="nav-link" href="{% url 'shop:store' %}">Store</a>
          </li>
          <li class="shop-second-nav-item nav-item">
            <a class="nav-link" href="{% url 'shop:all_sell' %}">Accounts</a>
          </li>
          
        </ul>
        <ul class="navbar-nav ml-auto nav-flex-icons d-flex flex-row justify-content-start">
                    
          
          
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    {% block content %}

    replace me

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script type="text/javascript">

      // if user clicks on the checkbox
      const showSellConfirmButtons = (id) => {
        console.log(id)
        $('#sell_options'+id).hide(); // hide the buttons
        $("#sell"+id).css("display", "block"); // view the buttons
    
      }

      const showSellAndPrintConfirmButtons = (id) => {
        console.log(id)
        $('#sell_options'+id).hide(); // hide the buttons
        $("#sell_print"+id).css("display", "block"); // view the buttons
    
      }

      const showDisableConfirmButtons = (id) => {
        console.log(id)
        $('#sell_options'+id).hide(); // hide the buttons
        $("#disable"+id).css("display", "block"); // view the buttons
    
      }

      const confirmSell = (id) => {

        let product_quantity = document.getElementById("product_quantity_input"+id).value;

        console.log(product_quantity)

        $.ajax({
          url: '/shop/sell/sellProduct/',
          type: 'GET',
          data: {
            'id': id, //pass the id to use in the backend
            'quantity': product_quantity,
          },        
        })
        .done(function(response){
          
          $('#sell'+id).hide()
          $('#sell_options'+id).css('display', "block")
          $('#sell_options'+id).show()
          window.location.reload(false); 
          // console.log('product_row'+response)
        })
        

      }

    // if user presses the No button
    const cancelSellChange = (id) => {
      console.log(id)
      $('#sell'+id).hide(); // hide the buttons
      $("#sell_options"+id).css("display", "block"); // view the checkbox
    }

    const cancelSellPrintChange = (id) => {
      console.log(id)
      $('#sell_print'+id).hide(); // hide the buttons
      $("#sell_options"+id).css("display", "block"); // view the checkbox
    }

    const canceldisableChange = (id) => {
      console.log(id)
      $('#disable'+id).hide(); // hide the buttons
      $("#sell_options"+id).css("display", "block"); // view the checkbox
    }
    </script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
    href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
        href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
        id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

<title>{% block title %}Title here {% endblock %}</title>
  </head>
  <body class="font-family-sans-serif">
    <nav class="navbar navbar-expand-lg navbar-dark p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'all_products' %}">MODERN</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          
          <li class="nav-item">
            <a class="nav-link" href="#">+8801986395483</a>
          </li>
          
          
        </ul>
        <div>
          <a class="float-right login_link" href="{% url 'account:login_page' %}">Login</a>
        </div>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    {% if 'login' not in request.path %}

    <nav class="second-navebar navbar navbar-expand-lg navbar-white p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="col-md-12 p-3 row justify-content-center top-search">
        <div class="col-md-7 justify-content-center">
          <div class="input-group px-5 top-search-bar">
            <form class="row col-md-12" method="get" action="{% url 'products:search_product' %}">
            <div class="form-outline col-md-10 ">
              <input type="search" id="search_product" name="product_search_parameter" class="form-control m-0 top-search-field" placeholder="S e a r c h" style="height: 40px;"/>
              
            </div>
            <div class="col-md-2">
              <button type="submit" class="btn top-search-button col-md-11">
                <i class="fa fa-search" style="color: rgb(255, 0, 0, .7);"></i>
              </button>
            </div>
          </form>
          </div>
        </div>
  
      </div>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01" style="height:71px;">
        
        <ul class="second-navebar-nav navbar-nav mr-auto mt-2 mt-lg-0">
          
          <li class="second-nav-item nav-item px-5 d-flex flex-column justify-content-center" style="height:71px;">
            <a class="nav-link mx-auto text-uppercase dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">All Categories</a>
            <div class="dropdown-menu custom-dropdown-menu show">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              
            </div>
          </li>          
        </ul>
        
        
      </div>
    </nav>

    

    <!-- here carousel part start-->
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active img-responsive">
          <img class="img-responsive center-block d-block w-100 h-100" src="{% static 'images/carousal1.jpg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 h-100" src="{% static '/images/carousal2.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100 h-100" src="{% static '/images/carousal3.jpg' %}" alt="Third slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <!-- carousel ends -->
    {% endif %}

    {% block content %}

    replace me

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}
    Modern Shop
{% endblock %}

{% block content %}

<p class="h4 text-dark display-4 ">Modern Cosmetics</P>

{% endblock %}

templates/super_admin_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
    href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
        href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
        id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

<title>{% block title %}Title here {% endblock %}</title>
  </head>
  <body class="font-family-sans-serif">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">MODERN</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active col">
            <a class="nav-link" href="{% url 'super_admin:dashboard' %}">Dashboard <span class="sr-only">(current)</span></a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{% url 'all-products' %}">All Products</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'super_admin:add_type_brand' %}">Product Type & Brand</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'super_admin:all_shop' %}">All Shop</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'super_admin:add_shop' %}">Add Shop</a>
          </li>
          
          
        </ul>

        <ul class="navbar-nav ml-auto nav-flex-icons d-flex flex-row justify-content-start">
                    
            <li class="nav-item active dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                <i class='fas fa-user-alt' style='font-size:18px;color:rgb(236, 236, 236)'></i>
                {{ request.user.first_name }}        
              <span class="sr-only">(current)</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'account:logout' %}" class="">
                   Log out
                </a>
            </li>
            
          </ul>
        <!-- <div>
          <a class="btn btn-info float-right" href="{% url 'account:logout' %}">Logout</a>
        </div> -->
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    {% block content %}

    replace me

    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>